language: php

php:
  - 7.0
  - nightly

addons:
  apt:
    packages:
      - valgrind

before_install:
  - phpenv config-rm xdebug.ini

install:
    - phpize
    - ./configure
    - make install
    - composer install --no-interaction

before_script:
  - echo "extension=ds.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - composer test
#  - composer memtest
