language: php

php:
  - 7.0
  - nightly

install:
    - phpize
    - ./configure
    - make install

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction
  - echo "extension=ds.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - composer test
