language: php

php:
  - 7.0
  - nightly

install:
    - phpize
    - ./configure
    - make install

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction

script:
  - php -d extension=ds.so `which composer` run-script test
